name: Test

on:
  push:
    branches:
      - "*"
    tags:
      - "!v*"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: "21.2.0"
          java: java11

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.6.0

      - name: Apply Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-graal-build-time-${{ hashFiles('deps.edn') }}
          restore-keys: "$graal-build-time-"

      - name: Setup build tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run native tests
        run: bb native-image-test
